from tkinter import *
import sqlite3
from tkinter import messagebox

wie = Tk()
wie.title("R.K.D School")
wie.geometry("1365x700")
wie.resizable(False, False)
task = Label(wie, text="R.K.D SCHOOL", font=("Times_New_Roman", 20), bg="blue", fg="white")
task.place(x=0, y=0, height=30, width=1365)
task_d = Label(wie, text="DATA VIEWS", font=("Times_New_Roman", 20), bg="blue", fg="white")
task_d.place(x=1000, y=70)
task_p = Label(wie, text="PRINCIPAL", font=("Times_New_Roman", 20), bg="blue", fg="white")
task_p.place(x=500, y=70)
conn = sqlite3.connect("school.db")
c = conn.cursor()
c.execute("CREATE TABLE School_Data([Id] INT NOT NULL PRIMARY KEY,NAME STRING,Father STRING,Mother STRING,ENGLISH INT, HINDI INT,MATH INT, PHYSICS INT,CHEMISTRY INT,TOTAL INT ,PERSENT INT)")


def submit():
    Id = id_e.get()
    Name = name_e.get()
    Father = father_e.get()
    Mother = mother_e.get()
    English = english_e.get()
    Hindi = hindi_e.get()
    Math = math_e.get()
    Physics = physics_e.get()
    Chemistry = chemistry_e.get()

    if Id == "":
        messagebox.showerror("Error", "please enter your Id")
    elif (Name == "") or (Name == IntVar):
        messagebox.showerror("Error", "please enter your Name")
    elif Father == "":
        messagebox.showerror("Error", "please enter your Father name")
    elif Mother == "":
        messagebox.showerror("Error", "please enter your Mother name")
    elif English == "":
        messagebox.showerror("Error", "please enter your English")
    elif Hindi == "":
        messagebox.showerror("Error", "please enter your Hindi")
    elif Math == "":
        messagebox.showerror("Error", "please enter your Math")
    elif Physics == "":
        messagebox.showerror("Error", "please enter your Physics")
    elif Chemistry == "":
        messagebox.showerror("Error", "please enter your Chemistry")
    else:
        Label(wie, text="Registration Successful", font="50", fg="green").place(x=150, y=580)
    Total = int(English) + int(Hindi) + int(Math) + int(Physics) + int(Chemistry)
    Present = (Total / 5)
    t = (Id, Name, Father, Mother, English, Hindi, Math, Physics, Chemistry, Total, Present)
    c.execute("INSERT INTO School_Data VALUES(?,?,?,?,?,?,?,?,?,?,?)", t)
    conn.commit()


id_e = Entry(wie)
id_e.place(x=100, y=140, height=30, width=180)
id_et = Label(wie, text="Id No")
id_et.place(x=0, y=140, height=30, width=80)
name_e = Entry(wie)
name_e.place(x=100, y=190, height=30, width=180)
name_et = Label(wie, text="Name")
name_et.place(x=0, y=190, height=30, width=80)
father_e = Entry(wie)
father_e.place(x=100, y=240, height=30, width=180)
father_et = Label(wie, text="Father")
father_et.place(x=0, y=240, height=30, width=80)
mother_e = Entry(wie)
mother_e.place(x=100, y=290, height=30, width=180)
mother_et = Label(wie, text="Mother")
mother_et.place(x=0, y=290, height=30, width=80)
english_e = Entry(wie)
english_e.place(x=100, y=340, height=30, width=180)
english_et = Label(wie, text="English", )
english_et.place(x=0, y=340, height=30, width=80)
hindi_e = Entry(wie)
hindi_e.place(x=100, y=390, height=30, width=180)
hindi_et = Label(wie, text="Hindi")
hindi_et.place(x=0, y=390, height=30, width=80)
math_e = Entry(wie)
math_e.place(x=100, y=440, height=30, width=180)
math_et = Label(wie, text="Math")
math_et.place(x=0, y=440, height=30, width=80)
physics_e = Entry(wie)
physics_e.place(x=100, y=490, height=30, width=180)
physics_et = Label(wie, text="Physics")
physics_et.place(x=0, y=490, height=30, width=80)
chemistry_e = Entry(wie)
chemistry_e.place(x=100, y=540, height=30, width=180)
chemistry_et = Label(wie, text="Chemistry")
chemistry_et.place(x=0, y=540, height=30, width=80)


def tab():
    cod = c_code.get()
    c_cod = int(cod)

    if c_cod == 12345:
        Label(wie, text="Password Successful", font="50", fg="green").place(x=500, y=110)

        def tab2():
            pk = b_enter1.get()
            Id = id_e.get()
            if pk in Id:
                Label(wie, text="Id Numer Successful", font="50", fg="green").place(x=500, y=167)
                enter_id = Label(wie, text="Id No ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_id.place(x=370, y=230, height=30, width=80)
                enter_name = Label(wie, text="Name ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_name.place(x=370, y=270, height=30, width=80)
                enter_father = Label(wie, text="Father ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_father.place(x=370, y=310, height=30, width=80)
                enter_mother = Label(wie, text="Mother ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_mother.place(x=370, y=350, height=30, width=80)
                enter_english = Label(wie, text="English ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_english.place(x=370, y=390, height=30, width=80)
                enter_Hindi = Label(wie, text="Hindi ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_Hindi.place(x=370, y=430, height=30, width=80)
                enter_math = Label(wie, text="Math ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_math.place(x=370, y=470, height=30, width=80)
                enter_physics = Label(wie, text="Physics ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_physics.place(x=370, y=510, height=30, width=80)
                enter_chemistry = Label(wie, text="Chemistry ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_chemistry.place(x=370, y=550, height=30, width=80)
                enter_total = Label(wie, text="Total Number ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_total.place(x=370, y=590, height=30, width=80)
                enter_present = Label(wie, text="Present ", font=("Times_New_Roman", 10), bg="blue", fg="white")
                enter_present.place(x=370, y=630, height=30, width=80)
                conn = sqlite3.connect("school.db")
                c = conn.cursor()
                c.execute("SELECT * FROM School_Data")
                r = c.fetchall()

                for i in r:
                    ide = Label(wie, text=i[0], font="time 10 bold")
                    ide.place(x=500, y=230, height=30, width=180)
                    name = Label(wie, text=i[1], font="time 10 bold")
                    name.place(x=500, y=270, height=30, width=180)
                    father = Label(wie, text=i[2], font="time 10 bold")
                    father.place(x=500, y=310, height=30, width=180)
                    mother = Label(wie, text=i[3], font="time 10 bold")
                    mother.place(x=500, y=350, height=30, width=180)
                    english = Label(wie, text=i[4], font="time 10 bold")
                    english.place(x=500, y=390, height=30, width=180)
                    hindi = Label(wie, text=i[5], font="time 10 bold")
                    hindi.place(x=500, y=430, height=30, width=180)
                    math = Label(wie, text=i[6], font="time 10 bold")
                    math.place(x=500, y=470, height=30, width=180)
                    physics = Label(wie, text=i[7], font="time 10 bold")
                    physics.place(x=500, y=510, height=30, width=180)
                    chemistry = Label(wie, text=i[8], font="time 10 bold")
                    chemistry.place(x=500, y=550, height=30, width=180)
                    t_total = Label(wie, text=i[9], font="time 10 bold")
                    t_total.place(x=500, y=590, height=30, width=180)
                    present = Label(wie, text=i[10], font="time 10 bold")
                    present.place(x=500, y=630, height=30, width=180)
                conn.commit()
                # conn.close()
            else:
                Label(wie, text="Id Numer Wrong", font="40", fg="green").place(x=500, y=167)

        b_button3 = Button(wie, text="SUBMIT", command=tab2)
        b_button3.place(x=700, y=190, height=30, width=100)
    else:
        Label(wie, text="Password Wrong", font="50", fg="green").place(x=500, y=110)


def data_view():
    pkm = b_enter2.get()
    Id = id_e.get()
    if pkm in Id:
        Label(wie, text="Id Numer successful", font="50", fg="green").place(x=1000, y=110)
        en_id = Label(wie, text="Id No ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_id.place(x=890, y=190, height=40, width=80)
        en_english = Label(wie, text="English ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_english.place(x=890, y=240, height=40, width=80)
        en_hindi = Label(wie, text="Hindi ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_hindi.place(x=890, y=290, height=40, width=80)
        en_math = Label(wie, text="Math ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_math.place(x=890, y=340, height=40, width=80)
        en_physics = Label(wie, text="Physics ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_physics.place(x=890, y=390, height=40, width=80)
        en_chemistry = Label(wie, text="Chemistry ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_chemistry.place(x=890, y=440, height=40, width=80)
        en_total = Label(wie, text="Total No ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_total.place(x=890, y=490, height=40, width=80)
        en_present = Label(wie, text="Present ", font=("Times_New_Roman", 10), bg="blue", fg="white")
        en_present.place(x=890, y=540, height=40, width=80)
        conn = sqlite3.connect("school.db")
        c = conn.cursor()
        c.execute("SELECT * FROM School_Data")
        r = c.fetchall()

        for i in r:
            ide = Label(wie, text=i[0], font="time 10 bold")
            ide.place(x=1010, y=190, height=30, width=180)
            english = Label(wie, text=i[4], font="time 10 bold")
            english.place(x=1010, y=240, height=30, width=180)
            hindi = Label(wie, text=i[5], font="time 10 bold")
            hindi.place(x=1010, y=290, height=30, width=180)
            math = Label(wie, text=i[6], font="time 10 bold")
            math.place(x=1010, y=340, height=30, width=180)
            physics = Label(wie, text=i[7], font="time 10 bold")
            physics.place(x=1010, y=390, height=30, width=180)
            chemistry = Label(wie, text=i[8], font="time 10 bold")
            chemistry.place(x=1010, y=440, height=30, width=180)
            t_total = Label(wie, text=i[9], font="time 10 bold")
            t_total.place(x=1010, y=490, height=30, width=180)
            present = Label(wie, text=i[10], font="time 10 bold")
            present.place(x=1010, y=540, height=30, width=180)

        conn.commit()
        conn.close()
    else:
        Label(wie, text="Id Numer Wrong", font="50", fg="green").place(x=1000, y=110)


c_code = Entry(wie, show="*")
c_code.place(x=500, y=140, height=30, width=180)
p_password = Label(wie, text="principal Password", font=("Times_New_Roman", 10), bg="blue", fg="white")
p_password.place(x=355, y=140, height=30, width=120)
b_submit = Button(wie, text="SUBMIT", command=tab)
b_submit.place(x=700, y=140, height=30, width=100)
e_id1 = Label(wie, text="Id No", font=("Times_New_Roman", 10), bg="blue", fg="white")
e_id1.place(x=370, y=190, height=30, width=100)
b_enter1 = Entry(wie)
b_enter1.place(x=500, y=190, height=30, width=180)
e_id2 = Label(wie, text="Id No", font=("Times_New_Roman", 10), bg="blue", fg="white")
e_id2.place(x=890, y=140, height=30, width=100)
b_enter2 = Entry(wie)
b_enter2.place(x=1010, y=140, height=30, width=180)
b_button1 = Button(wie, text="SUBMIT", command=data_view)
b_button1.place(x=1210, y=140, height=30, width=100)

b_button = Button(wie, text="SUBMIT", command=submit)
b_button.place(x=130, y=610, height=40, width=100)

mainloop()
